---
- name: DÃ©ploiement WordPress complet
  hosts: scaleway
  # hosts: local
  become: yes
  vars:
    wordpress_dir: "/opt/wordpress"
    project_dir: "{{ playbook_dir }}"
    nginx_http_port: 80
    nginx_https_port: 443
    nginx_domain: "darnetremi.fr"
    domain_name: "darnetremi.fr"
    email: "darnetremi@gmail.com"  
    nginx_container_name: "wordpress_nginx"
    # nginx_domain: localhost

  roles:
    - docker
    - db
    - wordpress
    - phpmyadmin
    - nginx
    - certbot
